### ISSUE TITLE
key not found: :ciphers (KeyError)

### ISSUE THREAD

**Issue by sharanraj124** [plattyp/addon#6]
Testing POST /heroku/resources
  Check response/Users/appleapple/.rvm/gems/ruby-2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:163:in `fetch': key not found: :ciphers (KeyError)

I run kensa test this type of error found in my mac.

**Comment by plattyp** [comment]
Thanks for pointing this out. I think my instructions on the README were missing a step of seeding your db with test data. I've updated the readme instructions to include that step.  I also added a little helper script to seed and run the tests. Let me know if that fixes your issue.

```
./bin/test
```
